const $=s=>document.querySelector(s);const poster=$('#poster'),portrait=$('#portrait'),leftLogo=$('#leftLogo'),rightLogo=$('#rightLogo');
const map={collegeInput:'collegeText',committeeInput:'committeeText',nameInput:'nameText',roleInput:'roleText',batchInput:'batchText',departmentInput:'departmentText'};const photo={scale:1,x:0,y:0};
function fit(el,min=11){let s=parseFloat(getComputedStyle(el).fontSize)||20;el.style.fontSize=s+'px';while(el.scrollWidth>el.clientWidth&&s>min){s-=.25;el.style.fontSize=s+'px'}}
for(const id in map){const i=$('#'+id),e=$('#'+map[id]);const up=()=>{e.textContent=i.value;e.style.fontSize='';requestAnimationFrame(()=>fit(e))};up();i.addEventListener('input',up)}
function apply(){portrait.style.transform=`translate(-50%,-50%) translate(${photo.x}px,${photo.y}px) scale(${photo.scale})`}
function action(a){if(a==='zoomIn')photo.scale=Math.min(4,photo.scale+.1);if(a==='zoomOut')photo.scale=Math.max(.5,photo.scale-.1);if(a==='left')photo.x-=12;if(a==='right')photo.x+=12;if(a==='up')photo.y-=12;if(a==='down')photo.y+=12;if(a==='reset')Object.assign(photo,{scale:1,x:0,y:0});apply()}
document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>action(b.dataset.photo));
function read(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
$('#photoUpload').onchange=e=>read(e.target.files[0],src=>{portrait.src=src;Object.assign(photo,{scale:1,x:0,y:0});apply()});
function transparentize(src,background,threshold=30){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),x=c.getContext('2d');c.width=im.naturalWidth;c.height=im.naturalHeight;x.drawImage(im,0,0);const d=x.getImageData(0,0,c.width,c.height),p=d.data,w=c.width,h=c.height,bg=background,q=[],seen=new Uint8Array(w*h);function near(i){return Math.abs(p[i]-bg[0])<threshold&&Math.abs(p[i+1]-bg[1])<threshold&&Math.abs(p[i+2]-bg[2])<threshold}for(let xx=0;xx<w;xx++){if(near(xx*4)){q.push(xx);seen[xx]=1}let i=((h-1)*w+xx)*4;if(near(i)&&!seen[(h-1)*w+xx]){q.push((h-1)*w+xx);seen[(h-1)*w+xx]=1}}for(let yy=0;yy<h;yy++){let a=yy*w,i=a*4;if(near(i)&&!seen[a]){q.push(a);seen[a]=1}let z=a+w-1,j=z*4;if(near(j)&&!seen[z]){q.push(z);seen[z]=1}}let k=0;while(k<q.length){const n=q[k++],y=Math.floor(n/w),xx=n%w;for(const m of [n-1,n+1,n-w,n+w]){if(m>=0&&m<w*h&&!seen[m]&&near(m*4)){seen[m]=1;q.push(m)}}}for(let i=0;i<w*h;i++)if(seen[i])p[i*4+3]=0;x.putImageData(d,0,0);resolve(c.toDataURL('image/png'))};im.onerror=reject;im.src=src})}
$('#leftLogoUpload').onchange=e=>read(e.target.files[0],src=>transparentize(src,[255,255,255]).then(s=>leftLogo.src=s));$('#rightLogoUpload').onchange=e=>read(e.target.files[0],src=>transparentize(src,[0,0,0]).then(s=>rightLogo.src=s));
function img(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function textFit(ctx,text,x,y,w,h,size,color,shadow){let s=size;ctx.font=`700 ${s}px Georgia,"Times New Roman",serif`;while(ctx.measureText(text).width>w&&s>11){s-=.25;ctx.font=`700 ${s}px Georgia,"Times New Roman",serif`}ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;if(shadow){ctx.shadowColor='rgba(0,0,0,.75)';ctx.shadowBlur=1;ctx.shadowOffsetY=2}ctx.fillText(text,x+w/2,y+h/2);ctx.shadowColor='transparent';ctx.shadowBlur=0;ctx.shadowOffsetY=0}
function gradient(ctx,x,y,w,h,stops){const g=ctx.createLinearGradient(0,y,0,y+h);stops.forEach(s=>g.addColorStop(s[0],s[1]));ctx.fillStyle=g;ctx.fillRect(x,y,w,h)}
async function render(){const W=1024,H=1536,c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');const base=await img(poster.style.backgroundImage?poster.style.backgroundImage.match(/url\("?(.*?)"?\)/)[1]:getComputedStyle(poster).backgroundImage.match(/url\("?(.*?)"?\)/)[1]);ctx.drawImage(base,0,0,W,H);
// Patches are deliberately inside the existing artwork shapes, never over their borders.
gradient(ctx,299,308,426,49,[[0,'#0b2d55'],[1,'#092e58']]);gradient(ctx,288,387,448,49,[[0,'#f6dfa7'],[.5,'#e9bf68'],[1,'#f5dca0']]);gradient(ctx,172,1075,676,82,[[0,'#0b355f'],[1,'#082d55']]);gradient(ctx,349,1182,326,39,[[0,'#f7e0aa'],[.5,'#e9c06b'],[1,'#f7e3b2']]);ctx.fillStyle='#fff';ctx.fillRect(304,1273,516,54);ctx.fillRect(304,1377,520,54);ctx.fillStyle='#fff';ctx.fillRect(48,108,166,225);ctx.fillRect(795,105,182,205);
const p=await img(portrait.src),iw=p.naturalWidth,ih=p.naturalHeight,fx=258,fy=516,fw=508,fh=497;ctx.save();ctx.beginPath();ctx.rect(fx,fy,fw,fh);ctx.clip();const fit=Math.max(fw/iw,fh/ih),dw=iw*fit,dh=ih*fit,cx=fx+fw/2,cy=fy+fh/2;ctx.translate(cx,cy);ctx.scale(photo.scale,photo.scale);ctx.translate(-cx,-cy);ctx.drawImage(p,fx+(fw-dw)/2+photo.x,fy+(fh-dh)/2+photo.y,dw,dh);ctx.restore();
const l=await img(leftLogo.src),r=await img(rightLogo.src);function contain(im,x,y,w,h){const s=Math.min(w/im.naturalWidth,h/im.naturalHeight),dw=im.naturalWidth*s,dh=im.naturalHeight*s;ctx.drawImage(im,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}contain(l,45,104,174,225);contain(r,792,101,186,215);
textFit(ctx,$('#collegeInput').value,300,309,424,48,26,'#fff',true);textFit(ctx,$('#committeeInput').value,290,387,444,49,28,'#092e58',false);textFit(ctx,$('#nameInput').value,174,1075,676,82,42,'#f7e9c7',true);textFit(ctx,$('#roleInput').value,350,1182,324,39,26,'#092e58',false);textFit(ctx,$('#batchInput').value,305,1274,514,53,22,'#0d315b',false);textFit(ctx,$('#departmentInput').value,305,1378,518,53,21,'#0d315b',false);return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('PNG Blob failed')),'image/png'))}
async function download(){const b=$('#downloadBtn');b.disabled=true;b.textContent='RENDERING…';try{const blob=await render();const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='political-science-forum-card.png';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000)}catch(e){console.error(e);$('#fallbackBtn').classList.remove('hidden')}finally{b.disabled=false;b.textContent='DOWNLOAD PNG'}}
$('#downloadBtn').onclick=download;$('#fallbackBtn').onclick=async()=>{const b=await render(),u=URL.createObjectURL(b);window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000)};apply();window.onresize=()=>Object.values(map).forEach(id=>fit($('#'+id)));
